// Generated by Wrangler on Fri Aug 16 2024 13:00:37 GMT-0400 (Atlantic Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  CACHE: KVNamespace
  BROWSER: DurableObjectNamespace<import("./src/index").Browser>
  MY_BROWSER: Fetcher
}
