// Generated by Wrangler on Wed Aug 14 2024 22:54:36 GMT-0400 (Atlantic Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  CACHE: KVNamespace
  BROWSER: DurableObjectNamespace<import("@/index").Browser>
  BROWSER_INSTANCE: Fetcher
}
