// Generated by Wrangler on Thu Aug 15 2024 18:51:17 GMT-0400 (Atlantic Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  CACHE: KVNamespace
  BROWSER: DurableObjectNamespace<import("./src/index").Browser>
  MY_BROWSER: Fetcher
}
